<a href="https://colab.research.google.com/github/ftomazetti/ChallengerNestle/blob/main/dev_io_coleta_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importações de pacotes

In [1]:
import pandas as pd
import requests
#import numpy as np
#from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LinearRegression
#import matplotlib.pyplot as plt

# **Coleta de dados**

In [22]:
from google.colab import files

uploaded = files.upload()

Saving tabela_paginas_38_a_40.csv to tabela_paginas_38_a_40.csv

In [23]:
! ls

sample_data  tabela_paginas_26_a_37.csv  tabela_paginas_38_a_40.csv

In [20]:
! rm -r -f *_38_a_40*.csv

In [8]:
url = 'tabela_paginas_26_a_37.csv'

df = pd.read_csv(url, sep=";", encoding="utf-8-sig")

print(df.head())

   Bloco Unidade  Vencimento  Valor do Boleto  Antecipado  Não Antecipado  \
0    2.0     405  10/08/2026           634.28      634.28             0.0
1    1.0     703  10/08/2026           634.28      634.28             0.0
2    2.0     406  10/08/2026           634.28      634.28             0.0
3    1.0     704  10/08/2026           765.75      765.75             0.0
4    2.0     407  10/08/2026           634.28      634.28             0.0

   A. Lançam. a Maior  A. Lançam. a Menor  Deságio  Motoboy  Impressão  \
0                 0.0                 0.0   -35.06      0.0        0.0
1                 0.0                 0.0   -35.06      0.0        0.0
2                 0.0                 0.0   -35.06      0.0        0.0
3                 0.0                 0.0   -35.06      0.0        0.0
4                 0.0                 0.0   -35.06      0.0        0.0

   Tar. Bancária  Tar. Correios  Tar. Adiant. Desc. de Pontual Pago
0            1.5            0.0           0.0             0.00  Sim
1            1.5            0.0           0.0             0.00  Sim
2            1.5            0.0           0.0             0.00  Sim
3            1.5            0.0           0.0             0.00  Sim
4            1.5            0.0           0.0             0.00  Sim

In [9]:
df.describe()

,Bloco,Valor do Boleto,Antecipado,Não Antecipado,A. Lançam. a Maior,A. Lançam. a Menor,Deságio,Motoboy,Impressão,Tar. Bancária,Tar. Correios,Tar. Adiant.
count,200.00000,200.000000,200.000000,200.0,200.0,200.000000,200.000000,200.0,200.000000,200.000000,200.0,200.0
mean,1.94018,701.227300,671.254650,0.0,0.0,-1.402400,-33.657600,0.0,0.060000,1.440000,0.0,0.0
std,0.78057,66.007311,151.831329,0.0,0.0,6.887569,6.887569,0.0,0.294676,0.294676,0.0,0.0
min,1.00000,613.800000,0.000000,0.0,0.0,-35.060000,-35.060000,0.0,0.000000,0.000000,0.0,0.0
25%,1.00000,634.280000,634.280000,0.0,0.0,0.000000,-35.060000,0.0,0.000000,1.500000,0.0,0.0
50%,2.00000,765.750000,634.280000,0.0,0.0,0.000000,-35.060000,0.0,0.000000,1.500000,0.0,0.0
75%,3.00000,765.750000,765.750000,0.0,0.0,0.000000,-35.060000,0.0,0.000000,1.500000,0.0,0.0
max,3.00000,765.750000,765.750000,0.0,0.0,0.000000,0.000000,0.0,1.500000,1.500000,0.0,0.0

In [24]:
url = 'tabela_paginas_38_a_40.csv'

df = pd.read_csv(url, sep=";", encoding="utf-8-sig")

print(df.head())

  Unidade  Reservadosespaçosdeeventos  Rateiocoberturadevagasdegaragem05de24  \
0  01-101                         NaN                                    NaN
1  01-102                         NaN                                    NaN
2  01-103                         NaN                                    NaN
3  01-104                         NaN                                    NaN
4  01-105                         NaN                                    NaN

   Taxadecondomínio  Controledeacesso(Parcela10/84-Loomy) Fundoreserva  \
0            494.18                                 109.9        30.20
1            494.18                                 109.9        30.20
2            494.18                                 109.9        30.20
3            494.18                                 109.9        30.20
4            494.18                                 109.9        30.20

  Multaporinfração Valortotalporunidade
0              NaN               634.29
1              NaN               634.29
2              NaN               634.29
3           965.52              1599.81
4              NaN               634.29

In [25]:
df.describe()

,Reservadosespaçosdeeventos,Rateiocoberturadevagasdegaragem05de24,Taxadecondomínio,Controledeacesso(Parcela10/84-Loomy)
count,0.0,130.000000,2.000000e+02,2.000000e+02
mean,NaN,103.153385,4.941800e+02,1.099000e+02
std,NaN,54.254933,2.222456e-12,1.709582e-13
min,NaN,0.000000,4.941800e+02,1.099000e+02
25%,NaN,131.470000,4.941800e+02,1.099000e+02
50%,NaN,131.470000,4.941800e+02,1.099000e+02
75%,NaN,131.470000,4.941800e+02,1.099000e+02
max,NaN,131.470000,4.941800e+02,1.099000e+02